### ISSUE TITLE
Getting no_method error on root path when trying to use

### ISSUE THREAD

**Issue by brlanier** [amco/biran#24]
```
rake aborted!
NoMethodError: undefined method `root_path' for #<Biran::Config:0x007fb9144bc6a0>
/Users/brian/repos/biran/lib/biran/config_defaults.rb:54:in `secrets_file'
/Users/brian/repos/biran/lib/biran/configurinator.rb:57:in `build_app_config'
/Users/brian/repos/biran/lib/biran/configurinator.rb:29:in `initialize'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:2:in `new'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:2:in `block in <top (required)>'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:1:in `<top (required)>'
/Users/brian/repos/biran/lib/biran/railtie.rb:8:in `block in <class:Railtie>'
/Users/brian/repos/cheddar2/Rakefile:6:in `<top (required)>'
/Users/brian/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/brian/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by brlanier** [comment]
Missed two values in config_defaults still calling root_path. Not sure how that got by my testing

**Comment by brlanier** [comment]
I think this can be closed
