### ISSUE TITLE
Running config:generate fails with an error

### ISSUE THREAD

**Issue by brlanier** [amco/biran#60]
```
rake aborted!
NoMethodError: undefined method `deep_merge!' for nil:NilClass
/Users/brian/repos/biran/lib/biran/configurinator.rb:58:in `build_app_config'
/Users/brian/repos/biran/lib/biran/configurinator.rb:20:in `initialize'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:2:in `new'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:2:in `block in <top (required)>'
/Users/brian/repos/biran/lib/tasks/biran_tasks.rake:1:in `<top (required)>'
/Users/brian/repos/biran/lib/biran/railtie.rb:8:in `load'
/Users/brian/repos/biran/lib/biran/railtie.rb:8:in `block in <class:Railtie>'
/Users/brian/repos/bs/Rakefile:6:in `<top (required)>'
/Users/brian/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/Users/brian/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by brlanier** [comment]
This is a bug added with the last change to the secrets stuff. If app_config does not have any contents in `secrets:` then the `app_config[:secrets]` section is nil by default and the code tries to do a deep_merge! on the nil object.
Need to allow for configs that are not using secrets at all or setup via app_config.

**Comment by brlanier** [comment]
This was handled in the above PR's
